FROM golang:latest

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

ARG REPO="github.com/Atsushi-Hasegawa/grpc"
RUN mkdir -p /root/.ssh
RUN chmod 0700 /root/.ssh
COPY .ssh/* /root/.ssh/

RUN mkdir -p /go/src/${REPO}
COPY . /go/src/${REPO}
WORKDIR /go/src/${REPO}
RUN make
RUN go build -o grpc-backend ./server/main.go && \
  mv ./grpc-backend /usr/local/bin/

EXPOSE 8080
CMD ["grpc-backend"]
